# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-10 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_friendlylink'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='emil',
            field=models.CharField(default=1, max_length=200, verbose_name='邮箱'),
            preserve_default=False,
        ),
    ]
